"""Hand tags for the pilot batch. Key: (year, variant, qid).

topics: primary syllabus sub-topics first (9708 syllabus 2026-28 numbering, which matches 2023-25).
cmd: primary command word, cmd2: secondary command word (the 'and consider...' part).
ao3: marks available for evaluation (AO3).
context: real-world context of the data response (blank for essays).
"""

TOPIC_NAMES = {
    '1.1': 'Scarcity, choice and opportunity cost',
    '1.2': 'Economic methodology',
    '1.3': 'Factors of production',
    '1.4': 'Resource allocation in different economic systems',
    '1.5': 'Production possibility curves',
    '1.6': 'Classification of goods and services',
    '2.1': 'Demand and supply curves',
    '2.2': 'PED, YED and XED',
    '2.3': 'Price elasticity of supply',
    '2.4': 'The interaction of demand and supply',
    '2.5': 'Consumer and producer surplus',
    '3.1': 'Reasons for government intervention in markets',
    '3.2': 'Methods and effects of government intervention in markets',
    '3.3': 'Addressing income and wealth inequality',
    '4.1': 'National income statistics',
    '4.2': 'Introduction to the circular flow of income',
    '4.3': 'AD and AS analysis',
    '4.4': 'Economic growth',
    '4.5': 'Unemployment',
    '4.6': 'Price stability',
    '5.1': 'Government macroeconomic policy objectives',
    '5.2': 'Fiscal policy',
    '5.3': 'Monetary policy',
    '5.4': 'Supply-side policy',
    '6.1': 'The reasons for international trade',
    '6.2': 'Protectionism',
    '6.3': 'Current account of the balance of payments',
    '6.4': 'Exchange rates',
    '6.5': 'Policies to correct current account imbalances',
}

UNIT_NAMES = {
    '1': 'Basic economic ideas and resource allocation',
    '2': 'The price system and the microeconomy',
    '3': 'Government microeconomic intervention',
    '4': 'The macroeconomy',
    '5': 'Government macroeconomic intervention',
    '6': 'International economic issues',
}

T = {
    # ---------- June 2025, 9708/21 — US inflation and the Federal Reserve ----------
    (2025, '21', '1(a)'): dict(topics=['4.6', '5.3'], sub=['4.6.1', '5.3.2'], cmd='Compare', cmd2='', ao3=0,
                               concepts=['inflation rate', 'interest rate', 'data comparison'], context='USA – inflation and the Federal Reserve'),
    (2025, '21', '1(b)'): dict(topics=['4.6'], sub=['4.6.2'], cmd='Explain', cmd2='', ao3=0,
                               concepts=['consumer price index', 'measurement difficulties'], context='USA – inflation and the Federal Reserve'),
    (2025, '21', '1(c)'): dict(topics=['4.6', '5.3'], sub=['4.6.1', '4.6.5', '5.3.3'], cmd='Consider', cmd2='', ao3=1,
                               concepts=['disinflation', 'deflation', 'consequences of inflation', 'contractionary monetary policy'], context='USA – inflation and the Federal Reserve'),
    (2025, '21', '1(d)'): dict(topics=['5.3', '4.3', '4.5'], sub=['5.3.3', '5.3.4', '4.3.12'], cmd='Assess', cmd2='', ao3=2,
                               concepts=['interest rates', 'recession', 'aggregate demand', 'interest elasticity'], context='USA – inflation and the Federal Reserve'),
    (2025, '21', '1(e)'): dict(topics=['5.3', '5.1', '4.6'], sub=['5.3.1', '5.1.1'], cmd='Assess', cmd2='', ao3=2,
                               concepts=['inflation target', 'central bank', 'inflation expectations', 'wage-price spiral'], context='USA – inflation and the Federal Reserve'),
    (2025, '21', '2(a)'): dict(topics=['1.5', '1.1'], sub=['1.5.2', '1.5.3', '1.5.4', '1.1.3'], cmd='Explain', cmd2='Consider', ao3=2,
                               concepts=['PPC', 'opportunity cost', 'movement within PPC', 'shift of PPC'], context=''),
    (2025, '21', '2(b)'): dict(topics=['1.5', '1.3', '4.4'], sub=['1.5.3', '1.3.1', '1.3.2', '4.4.4'], cmd='Assess', cmd2='', ao3=4,
                               concepts=['PPC shift', 'quantity of resources', 'quality of resources', 'technology'], context=''),
    (2025, '21', '3(a)'): dict(topics=['3.2', '2.4', '2.2'], sub=['3.2.2', '2.4.2', '2.2.7'], cmd='Explain', cmd2='Consider', ao3=2,
                               concepts=['subsidy', 'equilibrium price and quantity', 'PED', 'government expenditure on subsidy'], context=''),
    (2025, '21', '3(b)'): dict(topics=['3.2', '3.1', '1.6'], sub=['3.2.1', '3.2.6', '3.2.4', '3.1.2', '1.6.4'], cmd='Assess', cmd2='', ao3=4,
                               concepts=['indirect tax', 'demerit good', 'PED', 'information campaign', 'minimum price'], context=''),
    (2025, '21', '4(a)'): dict(topics=['4.2'], sub=['4.2.1', '4.2.2'], cmd='Explain', cmd2='Consider', ao3=2,
                               concepts=['circular flow', 'closed vs open economy', 'injections', 'leakages'], context=''),
    (2025, '21', '4(b)'): dict(topics=['6.2', '6.1'], sub=['6.2.3', '6.1.2'], cmd='Assess', cmd2='', ao3=4,
                               concepts=['free trade', 'protectionism', 'infant industry', 'dumping', 'specialisation'], context=''),
    (2025, '21', '5(a)'): dict(topics=['5.2'], sub=['5.2.1', '5.2.2', '5.2.3'], cmd='Explain', cmd2='Consider', ao3=2,
                               concepts=['budget surplus', 'budget deficit', 'government budget'], context=''),
    (2025, '21', '5(b)'): dict(topics=['5.2', '4.6', '4.5'], sub=['5.2.6', '5.2.7', '5.2.3'], cmd='Assess', cmd2='', ao3=4,
                               concepts=['expansionary fiscal policy', 'aggregate demand', 'national debt', 'demand-pull inflation'], context=''),

    # ---------- June 2026, 9708/21 — Inflation and economic growth in Japan ----------
    (2026, '21', '1(a)'): dict(topics=['4.6'], sub=['4.6.3'], cmd='Explain', cmd2='', ao3=0,
                               concepts=['real wages', 'money wages', 'nominal vs real'], context='Japan – inflation, low interest rates and growth'),
    (2026, '21', '1(b)'): dict(topics=['5.3'], sub=['5.3.2'], cmd='State', cmd2='', ao3=0,
                               concepts=['tools of monetary policy', 'money supply', 'credit regulations'], context='Japan – inflation, low interest rates and growth'),
    (2026, '21', '1(c)'): dict(topics=['6.4', '5.3'], sub=['6.4.2', '6.4.3', '6.4.4'], cmd='Explain', cmd2='Consider', ao3=1,
                               concepts=['exchange rate determination', 'depreciation', 'interest rates', 'currency demand and supply'], context='Japan – inflation, low interest rates and growth'),
    (2026, '21', '1(d)'): dict(topics=['5.3', '4.3'], sub=['5.3.4', '4.3.3', '4.3.5'], cmd='Assess', cmd2='', ao3=2,
                               concepts=['low interest rates', 'aggregate demand', 'consumption', 'investment', 'confidence'], context='Japan – inflation, low interest rates and growth'),
    (2026, '21', '1(e)'): dict(topics=['4.4', '4.6'], sub=['4.4.5'], cmd='Assess', cmd2='', ao3=2,
                               concepts=['consequences of economic growth', 'inflation', 'inequality', 'environment'], context='Japan – inflation, low interest rates and growth'),
    (2026, '21', '2(a)'): dict(topics=['1.6'], sub=['1.6.2', '1.6.3'], cmd='Explain', cmd2='Consider', ao3=2,
                               concepts=['public good', 'merit good', 'non-rival', 'non-excludable', 'health care'], context=''),
    (2026, '21', '2(b)'): dict(topics=['3.2', '3.1', '1.6'], sub=['3.2.1', '3.2.6', '3.1.2', '1.6.4'], cmd='Assess', cmd2='', ao3=4,
                               concepts=['demerit good', 'indirect tax', 'information campaign', 'PED'], context=''),
    (2026, '21', '3(a)'): dict(topics=['3.3'], sub=['3.3.3'], cmd='Explain', cmd2='Consider', ao3=2,
                               concepts=['income inequality', 'education and skills', 'technological change', 'discrimination'], context=''),
    (2026, '21', '3(b)'): dict(topics=['3.3', '5.2'], sub=['3.3.4', '5.2.4'], cmd='Assess', cmd2='', ao3=4,
                               concepts=['redistribution', 'minimum wage', 'progressive income tax', 'informal economy'], context=''),
    (2026, '21', '4(a)'): dict(topics=['4.5'], sub=['4.5.3', '4.5.4'], cmd='Explain', cmd2='Consider', ao3=2,
                               concepts=['frictional unemployment', 'structural unemployment', 'consequences of unemployment'], context=''),
    (2026, '21', '4(b)'): dict(topics=['5.2', '5.4', '4.5'], sub=['5.2.7', '5.4.3', '5.4.4', '4.5.3'], cmd='Assess', cmd2='', ao3=4,
                               concepts=['fiscal policy', 'supply-side policy', 'cyclical unemployment', 'structural unemployment'], context=''),
    (2026, '21', '5(a)'): dict(topics=['6.2'], sub=['6.2.2'], cmd='Explain', cmd2='Consider', ao3=2,
                               concepts=['embargo', 'export subsidy', 'tools of protection'], context=''),
    (2026, '21', '5(b)'): dict(topics=['6.2', '6.1'], sub=['6.2.3', '6.1.2'], cmd='Assess', cmd2='', ao3=4,
                               concepts=['free trade', 'protectionism', 'infant industry', 'dumping', 'strategic industry'], context=''),

    # ---------- June 2026, 9708/22 — Should Australia support the production of nickel? ----------
    (2026, '22', '1(a)'): dict(topics=['2.2'], sub=['2.2.2'], cmd='Calculate', cmd2='', ao3=0,
                               concepts=['PED calculation'], context='Australia – government support for nickel'),
    (2026, '22', '1(b)'): dict(topics=['2.2'], sub=['2.2.3', '2.2.4', '2.2.6'], cmd='State', cmd2='', ao3=0,
                               concepts=['PED interpretation', 'elastic vs inelastic', 'necessities'], context='Australia – government support for nickel'),
    (2026, '22', '1(c)'): dict(topics=['3.2', '2.4', '2.3'], sub=['3.2.2', '2.4.2', '2.3.4'], cmd='Explain', cmd2='Consider', ao3=1,
                               concepts=['subsidy', 'supply shift', 'PES', 'exports'], context='Australia – government support for nickel'),
    (2026, '22', '1(d)'): dict(topics=['5.2', '4.3', '6.3'], sub=['5.2.7', '4.3.12', '5.2.3'], cmd='Assess', cmd2='', ao3=2,
                               concepts=['government spending', 'aggregate demand', 'inflation', 'budget deficit', 'current account'], context='Australia – government support for nickel'),
    (2026, '22', '1(e)'): dict(topics=['6.1', '6.2'], sub=['6.1.1', '6.1.4', '6.2.3'], cmd='Assess', cmd2='', ao3=2,
                               concepts=['comparative advantage', 'specialisation', 'strategic industry', 'opportunity cost of subsidies'], context='Australia – government support for nickel'),
    (2026, '22', '2(a)'): dict(topics=['1.6', '3.2', '3.1'], sub=['1.6.2', '1.6.3', '3.2.6', '3.1.2'], cmd='Explain', cmd2='Consider', ao3=2,
                               concepts=['public good', 'merit good', 'free-rider problem', 'provision of information', 'subsidy'], context=''),
    (2026, '22', '2(b)'): dict(topics=['1.6', '1.4', '3.1'], sub=['1.6.2', '1.4.1', '1.4.2', '3.1.1'], cmd='Assess', cmd2='', ao3=4,
                               concepts=['public goods', 'mixed economy', 'market economy', 'planned economy', 'free-rider problem'], context=''),
    (2026, '22', '3(a)'): dict(topics=['2.4', '2.2', '2.1'], sub=['2.4.1', '2.4.2', '2.2.3', '2.1.5'], cmd='Explain', cmd2='Consider', ao3=2,
                               concepts=['market equilibrium', 'YED', 'normal good', 'inferior good', 'income'], context=''),
    (2026, '22', '3(b)'): dict(topics=['3.2', '3.1', '2.2', '2.3'], sub=['3.2.4', '3.2.5', '3.2.1', '3.2.2', '3.1.3'], cmd='Assess', cmd2='', ao3=4,
                               concepts=['maximum price', 'minimum price', 'buffer stocks', 'excess demand', 'excess supply'], context=''),
    (2026, '22', '4(a)'): dict(topics=['4.4', '1.3'], sub=['4.4.2', '4.4.3', '4.4.4', '1.3.1'], cmd='Explain', cmd2='Consider', ao3=2,
                               concepts=['real GDP', 'nominal GDP', 'causes of growth', 'quantity vs quality of resources'], context=''),
    (2026, '22', '4(b)'): dict(topics=['4.4'], sub=['4.4.5'], cmd='Assess', cmd2='', ao3=4,
                               concepts=['benefits of growth', 'costs of growth', 'developing economies', 'environment'], context=''),
    (2026, '22', '5(a)'): dict(topics=['4.2'], sub=['4.2.1', '4.2.2', '4.2.3'], cmd='Explain', cmd2='Consider', ao3=2,
                               concepts=['circular flow', 'open economy', 'closed economy', 'injections', 'leakages'], context=''),
    (2026, '22', '5(b)'): dict(topics=['5.2', '4.2', '5.1'], sub=['5.2.4', '5.2.5', '4.2.2', '5.1.1'], cmd='Assess', cmd2='', ao3=4,
                               concepts=['fiscal policy', 'injections', 'leakages', 'macroeconomic objectives', 'tariffs'], context=''),
}

# Issues to show reviewers (kept in the record so the front end can hide or flag them)
FLAGS = {
    (2025, '21', '1'): 'Published question paper has most of the Section A article and Table 1.1 removed for copyright; students cannot answer 1(a) from this copy.',
    (2026, '22', '1'): 'Published question paper has the Section A source text and Table 1.1 removed for copyright; students cannot answer 1(a)–(b) from this copy.',
    (2026, '22', '1(a)'): 'Mark scheme tolerance symbols (±) did not survive PDF extraction: shown as "(.0.2)" / "( 0.2)". Check against the PDF.',
}
